pipeline {
    agent any
    parameters {
        string(name: 'Greeting', defaultValue: '${github_repo}', description: 'How should I greet the world?')
    }
    stages {
        stage('Example') {
            steps {
                echo "${params.Greeting} World!"
            }
        }
    }
}
